version: "3"
services:

  redis:
    image: redis:4-alpine
    volumes:
      - /data/redis:/data
    networks:
      - db

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE="mathem"
    volumes:
       - /data/mysql:/var/lib/mysql
    networks:
      - db
    env_file:
      - ./.env

  certbot:
    image: certbot:latest
    command: certbot --nginx certonly
    volumes:
      - /data/certbot/letsencrypt/:/var/www/letsencrypt
      - /data/certbot/certs/:/var/certs
      - /data/letsencrypt/etc/:/etc/letsencrypt
      - /data/letsencrypt/var/:/var/lib/letsencrypt
    links:
      - nginx
    networks:
      - server

  nginx:
    image: enzomartin78/mathem-poc-nginx:master-latest
    volumes:
      - /data/nginx/logs/:/var/log/nginx
      - /data/certbot/letsencrypt/:/var/www/letsencrypt
      - /data/certbot/certs/:/var/certs
      - /data/letsencrypt/etc/:/etc/letsencrypt
      - /data/letsencrypt/var/:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    links:
      - service
    networks:
      - server

  service:
    image: enzomartin78/mathem-poc:master-latest
    environment:
      - NODE_ENV="production"
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      - db
      - server
    env_file:
      - ./.env

networks:
  server:
  db:
